### PR TITLE
card ui updated

### PR DESCRIPTION
**Pull request by Tausif4171**

### CODE REVIEW

**Comment by chentriangoes** [comment]
Not the collaborator of this project and this edit is behind the other update, so it's to be closed.

**Comment by Tausif4171** [comment]
okay but i want to contribute is there any work for me please let me know :)

**Comment by chentriangoes** [comment]
Hi Tausif,

Thank you for expressing your interest to make contribution to this project. However, this is a team project for a coding course, we are unable to have you in this occasion.

You are more than welcome to use the codes for your other occasions or to keep editing it as your feedback to our codes. Since we need to do the coding by ourselves, we are happy to take your codes, if simpler and better, as reference to shape this project.

Much appreciated again and have a great day.

Kind regards,
Yi-Tsun, on behalf of the team KCG

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Tausif4171** [comment]
Okay, Thankyou so much 😊

**Pull request closed without merging**
